site_name: Knowledge Bank
site_url: https://kaushal726.github.io/self-learning/
site_description: A Place for Knowledge Hub
site_author: Kaushal Raj

repo_url: https://github.com/kaushal726/self-learning
edit_uri: blob/master/docs/

theme:
  features:
    - header.autohide
  text: Roboto
  name: material
  features:
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Docs: docs.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaushal726
    - icon: fontawesome/brands/x-twitter
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kaushal-raj-074673213?utm_source=share&utm_campaign=share_via&utm_content=profile

markdown_extensions:
  - toc:
      permalink: "¶"
      toc_depth: 3
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/kaushal726">Kaushal Raj</a>.

plugins:
  - offline
  - search
  - git-revision-date
  - autorefs
  - git-authors
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
