site_name: Knowledge Bank
site_url: https://kaushal726.github.io/self-learning/
site_description: Place for Knowledge Hub.
site_author: Kaushal Raj

repo_url: https://github.com/kaushal726/self-learning
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics:
    gtag: "G-274394082"
  highlightjs: true
  hljs_languages:
    - javascript
    - python

nav:
  - Home: index.md
  - Docs: docs.md

markdown_extensions:
  - toc:
      permalink: "¶"
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs

copyright: Copyright &copy; 2024 <a href="https://github.com/kaushal726">Kaushal Raj</a>.
plugins:
  - search
  - redirects:
      redirect_maps:
        user-guide/plugins.md: dev-guide/plugins.md
        user-guide/custom-themes.md: dev-guide/themes.md
        user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
